# Generated by Django 4.0.6 on 2022-07-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileImgae',
            new_name='profileImage',
        ),
    ]
