# Generated by Django 4.0.6 on 2022-07-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blog_audience_blog_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='blogIdea',
        ),
    ]
