# Generated by Django 4.0.6 on 2022-07-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_topic_blog_blogidea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogSection',
            new_name='BlogSectionM',
        ),
    ]
