# Generated by Django 4.0.6 on 2022-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_profile_monthlycount_profile_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptionReference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
